/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Proov */

#ifndef _Included_Proov
#define _Included_Proov
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Proov
 * Method:    cppTukeldused
 * Signature: ([DDI)I
 */
JNIEXPORT jint JNICALL Java_Proov_cppTukeldused
  (JNIEnv *, jobject, jdoubleArray, jdouble, jint);

/*
 * Class:     Proov
 * Method:    cppJouame
 * Signature: (Ljava/lang/String;II[Ljava/lang/String;[[I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Proov_cppJouame
  (JNIEnv *, jobject, jstring, jint, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
