/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Proov */

#ifndef _Included_Proov
#define _Included_Proov
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Proov
 * Method:    prooviLoopi
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Proov_prooviLoopi
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
